### ISSUE TITLE
Clicking a building shows the list of events within that building

### ISSUE THREAD

**Issue by Romerico234** [curlyLasagna/COSC435_Project#16]
Create a class called struct called `Building`
`Building` should contain the following attributes
- name
- coordinates

Each `Building` is mapped to a map marker

Create a dictionary of key `building` with a value of list of events

When the user clicks on a building marker, display the list of events under that `Building` key

NOTE: This depends on how we do markers so its in the back burner for now

**Comment by curlyLasagna** [comment]
yoink
