### ISSUE TITLE
Refactor any views that aren't playing well with the standard event model

### ISSUE THREAD

**Issue by curlyLasagna** [curlyLasagna/COSC435_Project#54]
There are some events from events.tu that don't have location

**Comment by Romerico234** [comment]
Favoriting functionality broke

**Comment by curlyLasagna** [comment]
> Favoriting functionality broke

Rip, should've tested it. brb

**Comment by curlyLasagna** [comment]
Just pushed a quick fix in dev

**Comment by curlyLasagna** [comment]
I've set events.tu events that have a nil location be discarded but looking at the data being returned, some just have an empty string and no relevant geo information because those events are `online` events.

Creating a PR to discard online events

**Comment by curlyLasagna** [comment]
Fixed this with https://github.com/curlyLasagna/COSC435_Project/pull/57
